FROM golang:1.20 AS builder
WORKDIR /app
COPY pb /app/pb/
COPY *.go go.mod go.sum /app/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main

# use smaller one
FROM golang:1.20 AS runner
COPY --from=builder /app/main /main
# USER nobody
CMD ["/main"]
